export const ipcChannels = {
  listScreenSources: 'screen:list-sources',
  selectScreenSource: 'screen:select-source',
  clearScreenSource: 'screen:clear-source',
  getCaptureAuthorizationState: 'screen:get-authorization-state',
  exportDiagnostics: 'diagnostics:export',
  getTailscaleStatus: 'tailscale:get-status',
  hostSession: 'session:host',
  findSession: 'session:find',
  submitAnswer: 'session:submit-answer',
  stopHostedSession: 'session:stop-hosted',
  sessionAnswer: 'session:answer',
  toggleFullscreen: 'window:toggle-fullscreen',
  minimizeWindow: 'window:minimize',
  maximizeWindow: 'window:maximize',
  closeWindow: 'window:close',
  startFilteredSystemAudio: 'audio:start-filtered-system',
  stopFilteredSystemAudio: 'audio:stop-filtered-system',
  filteredAudioChunk: 'audio:filtered-chunk',
} as const;

