export const ipcChannels = {
  listScreenSources: 'screen:list-sources',
  selectScreenSource: 'screen:select-source',
  clearScreenSource: 'screen:clear-source',
  getCaptureAuthorizationState: 'screen:get-authorization-state',
  exportDiagnostics: 'diagnostics:export',
  getTailscaleStatus: 'tailscale:get-status',
  hostSession: 'session:host',
  findSession: 'session:find',
  submitAnswer: 'session:submit-answer',
  stopHostedSession: 'session:stop-hosted',
  sessionAnswer: 'session:answer',
  toggleFullscreen: 'window:toggle-fullscreen',
  setFullscreen: 'window:set-fullscreen',
  winKeyPressed: 'window:win-key-pressed',
  minimizeWindow: 'window:minimize',
  maximizeWindow: 'window:maximize',
  closeWindow: 'window:close',
  startFilteredSystemAudio: 'audio:start-filtered-system',
  stopFilteredSystemAudio: 'audio:stop-filtered-system',
  filteredAudioChunk: 'audio:filtered-chunk',
  setRemoteControlHostConfig: 'remote-input:set-config',
  setRemoteInputLock: 'remote-input:set-viewer-lock',
  capturedRemoteInput: 'remote-input:captured-key',
  remoteInputLockReleased: 'remote-input:viewer-lock-released',
  executeRemoteInput: 'remote-input:execute',
  resumeRemoteControlOverride: 'remote-input:resume-override',
  remoteControlStatusChanged: 'remote-input:status-changed',
} as const;

